### PR TITLE
Refactor for EPEL package

### PR DESCRIPTION
**Pull request by gsanchietti**
Refactor `nethserver-squidguard` to make it work with `ufdbGuard` package from EPEL:
- remove directories that are now part of ufdbGuard package
- fix changed path
- alias systemd unit
- replace `ufdbsignal` with `pkill`

The UI and events seem to work, but I didn't tested if the daemon does its job.

NethServer/dev#6243

### CODE REVIEW

**Comment by gsanchietti** [comment]
Please @filippocarletti put it in "Ready to review" state after further checks

**Comment by gsanchietti** [comment]
I've found that `ufdbGuard` still complain about permission on creating PID file.
I couldn't resolve it neither adding this config `/usr/lib/tmpfiles.d/ufdbGuard.conf`:
```
d /var/run/ufdbguard 0750 ufdb ufdb
```

So even if the unit is started, the daemon is not really working.

**Comment by mrmarkuz** [comment]
Strange, after adding the directory with right permissions ufdb service starts correctly.

```
mkdir /var/run/ufdbguard
chown ufdb:ufdb /var/run/ufdbguard
chmod 750 /var/run/ufdbguard
```

**Comment by filippocarletti** [comment]
Adding a systemd tmpfile as above fixed the problem for me.
I've filed a bug upstream:
https://bugzilla.redhat.com/show_bug.cgi?id=1864950

**Comment by filippocarletti** [comment]
We also need to remove "our" logrotate config file, which is a template:
`/etc/e-smith/templates/etc/logrotate.d/squidGuard/10base`

**Pull request merged**
