### PR TITLE
remove -P option as it stops squidguard rebuilding the url/domain dat…

### PR DESCRIPTION
**Pull request by darkspr1te**
-P option breaks squid db rebuild

### CODE REVIEW

**Comment by filippocarletti** [comment]
I understand the fix, but can't reproduce the error/problem.
How could I reproduce the error?
Thanks.

**Comment by darkspr1te** [comment]
not a available option 
[root@server ~]# squidGuard -v
SquidGuard: 1.3 Berkeley DB 4.7.25: (June 10, 2015)
[root@server ~]# squidGuard --help
squidGuard: invalid option -- '-'
Usage: squidGuard [-u] [-C block] [-t time] [-c file] [-v] [-d]
Options:
  -v          : show version number
  -d          : all errors to stderr
  -c file     : load alternate configfile
  -t time     : specify startup time in the format: yyyy-mm-ddTHH:MM:SS
  -u          : update .db files from .diff files
  -C file|all : create new .db files from urls/domain files
                specified in "file".

**Comment by filippocarletti** [comment]
root@nethsecurity ~]# squidGuard -v
SquidGuard: 1.4 Berkeley DB 4.7.25: (June 10, 2015)
[root@nethsecurity ~]# squidGuard --help
squidGuard: invalid option -- '-'
Usage: squidGuard [-u] [-C block] [-t time] [-c file] [-v] [-d] [-P]
Options:
  -v          : show version number
  -d          : all errors to stderr
  -b          : switch on the progress bar when updating the blacklists
  -c file     : load alternate configfile
  -t time     : specify startup time in the format: yyyy-mm-ddTHH:MM:SS
  -u          : update .db files from .diff files
  -C file|all : create new .db files from urls/domain files
                specified in "file".
  -P          : do not go into emergency mode when an error with the 
                blacklists is encountered.


We never released squidGuard 1.3, epel has v1.4 since 2012, before we started using squidGuard in NethServer.
Could you please show output of
rpm -qi squidGuard

**Comment by darkspr1te** [comment]
After disabling rpmforge repo, removing and reinstalling squidGuard the issue is resolved. The issue only happens if the system is installed via USB with default kickstart.cfg and not nethserver kickstart. Issue is user error and not a bug. Issue can be closed

**Pull request closed without merging**
